image: node:10.11

services:
  - postgres

variables:
    ENV: test
    POSTGRES_DB_URL: postgres://db_user:fakepassword@postgres:5432/v4l
    POSTGRES_DB: v4l
    POSTGRES_USER: db_user
    POSTGRES_PASSWORD: fakepassword


cache:
  paths:
  - node_modules/



test:
  before_script:
    - npm install
    - npm run sync
  script:
    - npm run lint
    - npm run test

codequality:
  before_script:
    - npm install
    - npm run sync
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
  script:
    - npm run test -- --coverage
  after_script:
    - ./cc-test-reporter after-build --exit-code $?
