version: '3'

services:

  db:
    image: postgres
    container_name: vote4lunch_postgres_db
    restart: always
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: fakepassword
      POSTGRES_DB: vote4lunch
    volumes:
      - data-vote4lunch:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  data-vote4lunch:
    external: true
